version: "3.9"

services:
#  elasticmq:
#    image: softwaremill/elasticmq-native
#    ports:
#      - '9324:9324'
#      - '9325:9325'
#    volumes:
#      - ./volumes/elasticmq/elasticmq.conf:/opt/elasticmq.conf
#    networks:
#      - https_proxy
#      - project_capstone
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data
  keycloak:
    image: bitnami/keycloak:19
    depends_on: [ 'postgresql' ]
    environment:
      - TZ=Asia/Singapore
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=EsF^I2Y9kV0*
    ports:
      - 8180:8180
      - 8080:8080
    volumes:
      - ./docker/volumes/keycloak/configuration:/bitnami/keycloak/configuration
  orders:
    image: maven:3.8-jdk-11
    depends_on:
      - keycloak
      # - elasticmq
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        cd /var/www/app
        mvn -f ./03-order-matching-service-api/pom.xml -B --no-transfer-progress -Dmaven.test.skip=true install
        mvn -f ./03-order-matching-service-api/pom.xml package
        mvn -f ./03-order-matching-service/pom.xml -B --no-transfer-progress -Dmaven.test.skip=true install
        mvn -f ./03-order-matching-service/pom.xml -e -P docker spring-boot:run
    ports:
      - 8880:8880
    volumes:
      - ./back-end/project-capstone/03-nus-order-matching-service:/var/www/app
      - .maven-repository:/root/.m2
  # web_frontend:
  #   image: node:16
  #   entrypoint: [ "/bin/bash", "-c" ]
  #   command:
  #     - |
  #       cd /var/www/app
  #       npm install
  #       npm run serve
  #   ports:
  #     - '8888:8080'
  #   volumes:
  #     - ./front-end:/var/www/app

volumes:
  maven-repository:
    external: false
